# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 20:45
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160214_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='date',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('carousel', wagtail.wagtailcore.blocks.StreamBlock((('body', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('headline', wagtail.wagtailcore.blocks.CharBlock(help_text='The main, all caps text of the frame.', required=True)), ('tagline', wagtail.wagtailcore.blocks.TextBlock(help_text='The smaller, regular cased text under the headline.')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text='The image serving as the background of the frame. Minimum 1080 pixels wide.', required=True)), ('color', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('dark', 'Dark'), ('light', 'Light')], icon='cog')), ('call_to_action', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('uri', wagtail.wagtailcore.blocks.URLBlock(required=True)), ('text', wagtail.wagtailcore.blocks.CharBlock(required=True))), classname='call_to_action'), help_text='The large button calling to user to act.The last one in the list receives the most emphasis.')), ('signup_form', wagtail.wagtailcore.blocks.BooleanBlock(help_text='Check to display an email signup form in this frame.', required=False)))), help_text='A horizontal scrolling set of images with text overlaid.')),))), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())), blank=True),
        ),
    ]
