# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 18:55
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20160220_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title')), (b'carousel', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'headline', wagtail.wagtailcore.blocks.CharBlock(help_text=b'The main, all caps text of the frame.', required=True)), (b'taglines', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(help_text=b'The smaller, regular cased text under the headline.'))), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text=b'The image serving as the background of the frame. Minimum 1080 pixels wide.', required=True)), (b'color', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'dark', b'Dark'), (b'light', b'Light')], icon=b'cog')), (b'call_to_action', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'uri', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'text', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'button_icon', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'color', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'black', b'Black'), (b'white', b'White')])), (b'size', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[(b'lg', b'Large'), (b'md', b'Medium'), (b'sm', b'Small')]))]))), (b'signup_form', wagtail.wagtailcore.blocks.BooleanBlock(help_text=b'Check to display an email signup form in this frame.', required=False))]), help_text=b'A horizontal scrolling set of images with text overlaid.', icon=b'cogs', template=b'blocks/carousel.html')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock())], blank=True),
        ),
    ]
