# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('home', '0037_auto_20160319_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
