# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('home', '0043_auto_20160328_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServicesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics', models.CharField(help_text='Your Google Analytics UA', max_length=255)),
                ('google_tag_manager', models.CharField(help_text='Your Google Tag Manager GTM ID', max_length=255)),
                ('optimizely', models.CharField(help_text='Your Optimizely project ID', max_length=255)),
                ('disqus', models.CharField(help_text='Your Disqus community name', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(help_text='Your Facebook handle', max_length=255)),
                ('instagram', models.CharField(help_text='Your Instagram handle', max_length=255)),
                ('twitter', models.CharField(help_text='Your Twitter handle', max_length=255)),
                ('github', models.CharField(help_text='Your GitHub username', max_length=255)),
                ('soundcloud', models.CharField(help_text='Your SoundCloud username', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
