# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_externalservicessettings_socialmediasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalservicessettings',
            name='disqus',
            field=models.CharField(blank=True, help_text='Your Disqus community name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='externalservicessettings',
            name='google_analytics',
            field=models.CharField(blank=True, help_text='Your Google Analytics UA', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='externalservicessettings',
            name='google_tag_manager',
            field=models.CharField(blank=True, help_text='Your Google Tag Manager GTM ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='externalservicessettings',
            name='optimizely',
            field=models.CharField(blank=True, help_text='Your Optimizely project ID', max_length=255, null=True),
        ),
    ]
