# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20160328_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.CharField(blank=True, help_text='Your Facebook handle', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='github',
            field=models.CharField(blank=True, help_text='Your GitHub username', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.CharField(blank=True, help_text='Your Instagram handle', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='soundcloud',
            field=models.CharField(blank=True, help_text='Your SoundCloud username', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.CharField(blank=True, help_text='Your Twitter handle', max_length=255, null=True),
        ),
    ]
